import type { ThemeConfig } from './themeConfig'
import type { ExtractedColor } from './types'

export interface SVGExportData {
  themeConfig: ThemeConfig
  colors: ExtractedColor[]
  darkMode: boolean
  previewMode: string
  backgroundStyle: string
  luminosity: number
  customGradient: string | null
}

/**
 * Generate SVG representation of the preview theme
 * This creates a compact SVG that can be used to recreate the preview
 */
export function generatePreviewSVG(data: SVGExportData): string {
  const {
    themeConfig,
    colors,
    darkMode,
    previewMode,
    backgroundStyle,
    luminosity,
    customGradient,
  } = data

  // Extract theme colors
  const primaryColor = themeConfig.colors.primary || colors[0]?.hex || '#000000'
  const secondaryColor = themeConfig.colors.secondary || colors[1]?.hex || '#666666'
  const accentColor = themeConfig.colors.accent || colors[2]?.hex || '#888888'
  const backgroundColor = darkMode ? '#0a0a0a' : '#ffffff'
  const foregroundColor = darkMode ? '#ffffff' : '#0a0a0a'

  // Create SVG with embedded theme data
  const svg = `<?xml version="1.0" encoding="UTF-8"?>
<svg width="1200" height="800" viewBox="0 0 1200 800" xmlns="http://www.w3.org/2000/svg">
  <!-- Theme Preview Export -->
  <!-- Generated by Pawlette - Do not edit manually -->
  
  <!-- Metadata -->
  <metadata>
    <theme-config>
      ${JSON.stringify(themeConfig, null, 2)}
    </theme-config>
    <colors>
      ${JSON.stringify(colors, null, 2)}
    </colors>
    <settings>
      ${JSON.stringify({ darkMode, previewMode, backgroundStyle, luminosity, customGradient }, null, 2)}
    </settings>
  </metadata>
  
  <!-- Defs -->
  <defs>
    ${generateGradientDefs(colors, customGradient)}
    ${generatePatternDefs()}
  </defs>
  
  <!-- Background -->
  <rect width="1200" height="800" fill="${backgroundColor}"/>
  
  ${backgroundStyle === 'gradient' || backgroundStyle === 'mesh'
      ? `<rect width="1200" height="800" fill="url(#bg-gradient)"/>`
      : ''
    }
  
  <!-- Preview Content -->
  <g id="preview-content">
    ${generatePreviewContent(previewMode, { primaryColor, secondaryColor, accentColor, foregroundColor, darkMode })}
  </g>
  
  <!-- Color Palette Reference -->
  <g id="color-palette" transform="translate(50, 720)">
    ${colors.map((color, i) => `
      <rect x="${i * 40}" y="0" width="35" height="60" fill="${color.hex}" rx="4"/>
      <text x="${i * 40 + 17.5}" y="75" fill="${foregroundColor}" font-size="10" text-anchor="middle" font-family="monospace">${color.hex}</text>
    `).join('')}
  </g>
</svg>`

  return svg
}

function generateGradientDefs(colors: ExtractedColor[], customGradient: string | null): string {
  if (customGradient) {
    return `<linearGradient id="bg-gradient" x1="0%" y1="0%" x2="100%" y2="100%">
      <!-- Custom gradient applied -->
    </linearGradient>`
  }

  if (colors.length < 2) return ''

  return `<linearGradient id="bg-gradient" x1="0%" y1="0%" x2="100%" y2="100%">
    ${colors.slice(0, 4).map((color, i, arr) =>
    `<stop offset="${(i / Math.max(arr.length - 1, 1)) * 100}%" stop-color="${color.hex}"/>`
  ).join('\n    ')}
  </linearGradient>`
}

function generatePatternDefs(): string {
  return `<pattern id="grid-pattern" x="0" y="0" width="40" height="40" patternUnits="userSpaceOnUse">
    <path d="M 40 0 L 0 0 0 40" fill="none" stroke="currentColor" stroke-width="0.5" opacity="0.1"/>
  </pattern>`
}

function generatePreviewContent(
  previewMode: string,
  colors: { primaryColor: string; secondaryColor: string; accentColor: string; foregroundColor: string; darkMode: boolean }
): string {
  const { primaryColor, secondaryColor, accentColor, foregroundColor, darkMode } = colors

  switch (previewMode) {
    case 'landing':
      return `
        <!-- Hero Section -->
        <rect x="100" y="100" width="1000" height="400" fill="${primaryColor}" opacity="0.1" rx="12"/>
        <text x="600" y="200" fill="${foregroundColor}" font-size="48" font-weight="bold" text-anchor="middle" font-family="system-ui">
          Your Brand Here
        </text>
        <text x="600" y="260" fill="${foregroundColor}" font-size="18" text-anchor="middle" font-family="system-ui" opacity="0.8">
          Beautiful colors, beautiful design
        </text>
        
        <!-- CTA Button -->
        <rect x="500" y="320" width="200" height="50" fill="${primaryColor}" rx="8"/>
        <text x="600" y="352" fill="white" font-size="16" font-weight="600" text-anchor="middle" font-family="system-ui">
          Get Started
        </text>
        
        <!-- Accent Elements -->
        <circle cx="200" cy="550" r="40" fill="${accentColor}" opacity="0.3"/>
        <circle cx="1000" cy="550" r="60" fill="${secondaryColor}" opacity="0.2"/>
      `

    case 'dashboard':
      return `
        <!-- Header Bar -->
        <rect x="80" y="80" width="1040" height="60" fill="${primaryColor}" opacity="0.9" rx="8"/>
        <text x="120" y="117" fill="white" font-size="18" font-weight="600" font-family="system-ui">
          Dashboard
        </text>
        
        <!-- Sidebar -->
        <rect x="80" y="160" width="200" height="520" fill="${secondaryColor}" opacity="0.1" rx="8"/>
        
        <!-- Content Cards -->
        <rect x="300" y="160" width="360" height="240" fill="${accentColor}" opacity="0.05" rx="8"/>
        <rect x="680" y="160" width="360" height="240" fill="${accentColor}" opacity="0.05" rx="8"/>
        <rect x="300" y="420" width="360" height="240" fill="${accentColor}" opacity="0.05" rx="8"/>
        <rect x="680" y="420" width="360" height="240" fill="${accentColor}" opacity="0.05" rx="8"/>
        
        <!-- Stats -->
        <text x="480" y="280" fill="${primaryColor}" font-size="36" font-weight="bold" text-anchor="middle" font-family="system-ui">
          1,234
        </text>
      `

    case 'card':
      return `
        <!-- Card Container -->
        <rect x="400" y="200" width="400" height="400" fill="${foregroundColor}" opacity="${darkMode ? '0.05' : '0.95'}" rx="16" stroke="${primaryColor}" stroke-width="2"/>
        
        <!-- Header -->
        <circle cx="600" cy="280" r="40" fill="${primaryColor}"/>
        <text x="600" y="360" fill="${foregroundColor}" font-size="24" font-weight="600" text-anchor="middle" font-family="system-ui">
          Card Title
        </text>
        <text x="600" y="390" fill="${foregroundColor}" font-size="14" text-anchor="middle" font-family="system-ui" opacity="0.6">
          Card description text
        </text>
        
        <!-- Accent Line -->
        <line x1="440" y1="430" x2="760" y2="430" stroke="${accentColor}" stroke-width="2"/>
        
        <!-- Action Button -->
        <rect x="500" y="500" width="200" height="40" fill="${primaryColor}" rx="6"/>
        <text x="600" y="527" fill="white" font-size="14" font-weight="600" text-anchor="middle" font-family="system-ui">
          Action
        </text>
      `

    default:
      return `
        <!-- Default Preview -->
        <text x="600" y="400" fill="${foregroundColor}" font-size="24" text-anchor="middle" font-family="system-ui">
          Preview Mode: ${previewMode}
        </text>
      `
  }
}

/**
 * Export theme data as JSON for programmatic use
 */
export function exportThemeData(data: SVGExportData): string {
  return JSON.stringify(data, null, 2)
}

/**
 * Parse theme data from SVG metadata
 */
export function parseThemeFromSVG(svgContent: string): SVGExportData | null {
  try {
    const parser = new DOMParser()
    const doc = parser.parseFromString(svgContent, 'image/svg+xml')

    const themeConfigEl = doc.querySelector('theme-config')
    const colorsEl = doc.querySelector('colors')
    const settingsEl = doc.querySelector('settings')

    if (!themeConfigEl || !colorsEl || !settingsEl) {
      return null
    }

    const themeConfig = JSON.parse(themeConfigEl.textContent || '{}')
    const colors = JSON.parse(colorsEl.textContent || '[]')
    const settings = JSON.parse(settingsEl.textContent || '{}')

    return {
      themeConfig,
      colors,
      darkMode: settings.darkMode,
      previewMode: settings.previewMode,
      backgroundStyle: settings.backgroundStyle,
      luminosity: settings.luminosity,
      customGradient: settings.customGradient,
    }
  } catch (error) {
    console.error('Failed to parse theme from SVG:', error)
    return null
  }
}

/**
 * Download SVG file
 */
export function downloadSVG(svgContent: string, filename: string) {
  const blob = new Blob([svgContent], { type: 'image/svg+xml' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}
